name: deploy

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - run: docker build . -t abhitheq/nextjs-app-github-actions
    - run: echo "${{secrets.DOCKERHUB_PASSKEY}}" | docker login -u ${{secrets.DOCKERHUB_USERNAME}} --password-stdin
    - run: docker push abhitheq/nextjs-app-github-actions:latest  